//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MME.Hercules.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SoundResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SoundResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MME.Hercules.Properties.SoundResources", typeof(SoundResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cameraclick.wav.
        /// </summary>
        internal static string CAMERA_CLICK {
            get {
                return ResourceManager.GetString("CAMERA_CLICK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choosebackground.wav.
        /// </summary>
        internal static string CHOOSE_BACKGROUND {
            get {
                return ResourceManager.GetString("CHOOSE_BACKGROUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to countdown.wav.
        /// </summary>
        internal static string COUNTDOWN {
            get {
                return ResourceManager.GetString("COUNTDOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to developing.wav.
        /// </summary>
        internal static string DEVELOPING_PLEASE_WAIT {
            get {
                return ResourceManager.GetString("DEVELOPING_PLEASE_WAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enteremail.wav.
        /// </summary>
        internal static string ENTER_EMAIL {
            get {
                return ResourceManager.GetString("ENTER_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fourcount.wav.
        /// </summary>
        internal static string FOUR_COUNT {
            get {
                return ResourceManager.GetString("FOUR_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getready.wav.
        /// </summary>
        internal static string GET_READY {
            get {
                return ResourceManager.GetString("GET_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to picked.wav.
        /// </summary>
        internal static string ITEM_SELECTED {
            get {
                return ResourceManager.GetString("ITEM_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unpicked.wav.
        /// </summary>
        internal static string ITEM_UNSELECTED {
            get {
                return ResourceManager.GetString("ITEM_UNSELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to picked.wav.
        /// </summary>
        internal static string KEY_CLICK {
            get {
                return ResourceManager.GetString("KEY_CLICK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lineupeyes.wav.
        /// </summary>
        internal static string LINE_UP_EYES {
            get {
                return ResourceManager.GetString("LINE_UP_EYES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to onecount.wav.
        /// </summary>
        internal static string ONE_COUNT {
            get {
                return ResourceManager.GetString("ONE_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photoscomplete.wav.
        /// </summary>
        internal static string PHOTOS_COMPLETE {
            get {
                return ResourceManager.GetString("PHOTOS_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photosdevelopedquick.wav.
        /// </summary>
        internal static string PHOTOS_DEVELOPED_QUICK {
            get {
                return ResourceManager.GetString("PHOTOS_DEVELOPED_QUICK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pickfavorite.wav.
        /// </summary>
        internal static string PICK_FAVORITE {
            get {
                return ResourceManager.GetString("PICK_FAVORITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pickupphotos.wav.
        /// </summary>
        internal static string PICK_UP_PHOTOS {
            get {
                return ResourceManager.GetString("PICK_UP_PHOTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to processingphotos.wav.
        /// </summary>
        internal static string PROCESSING_PHOTOS {
            get {
                return ResourceManager.GetString("PROCESSING_PHOTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to roomnumber.wav.
        /// </summary>
        internal static string ROOM_NUMBER {
            get {
                return ResourceManager.GetString("ROOM_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selectphototype.wav.
        /// </summary>
        internal static string SELECT_PHOTO_TYPE {
            get {
                return ResourceManager.GetString("SELECT_PHOTO_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selectphototype_wsepia.wav.
        /// </summary>
        internal static string SELECT_PHOTO_TYPE_W_SEPIA {
            get {
                return ResourceManager.GetString("SELECT_PHOTO_TYPE_W_SEPIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selection.wav.
        /// </summary>
        internal static string SELECTION_BUTTON {
            get {
                return ResourceManager.GetString("SELECTION_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to onemoretime.wav.
        /// </summary>
        internal static string TAKE_PHOTO_ONE_MORE_TIME {
            get {
                return ResourceManager.GetString("TAKE_PHOTO_ONE_MORE_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to threemoretimes.wav.
        /// </summary>
        internal static string TAKE_PHOTO_THREE_MORE_TIMES {
            get {
                return ResourceManager.GetString("TAKE_PHOTO_THREE_MORE_TIMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thanks.wav.
        /// </summary>
        internal static string THANK_YOU_FOR_TAKING_PHOTOS {
            get {
                return ResourceManager.GetString("THANK_YOU_FOR_TAKING_PHOTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to threecount.wav.
        /// </summary>
        internal static string THREE_COUNT {
            get {
                return ResourceManager.GetString("THREE_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to twocount.wav.
        /// </summary>
        internal static string TWO_COUNT {
            get {
                return ResourceManager.GetString("TWO_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to welcome.wav.
        /// </summary>
        internal static string WELCOME {
            get {
                return ResourceManager.GetString("WELCOME", resourceCulture);
            }
        }
    }
}
