//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MME.Hercules.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SpeechResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SpeechResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MME.Hercules.Properties.SpeechResources", typeof(SpeechResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now it is time to select your four custom backdrops..
        /// </summary>
        internal static string BACKGROUND {
            get {
                return ResourceManager.GetString("BACKGROUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four, Three, Two, One!.
        /// </summary>
        internal static string COUNTDOWN {
            get {
                return ResourceManager.GetString("COUNTDOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos developed in just 15 seconds! .
        /// </summary>
        internal static string DEVELOPING_PLEASE_WAIT {
            get {
                return ResourceManager.GetString("DEVELOPING_PLEASE_WAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email address, so we can get started..
        /// </summary>
        internal static string ENTEREMAIL {
            get {
                return ResourceManager.GetString("ENTEREMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Ready!.
        /// </summary>
        internal static string GET_READY {
            get {
                return ResourceManager.GetString("GET_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos Complete!.
        /// </summary>
        internal static string PHOTOS_COMPLETE {
            get {
                return ResourceManager.GetString("PHOTOS_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now it is time to pick your favorite photo..
        /// </summary>
        internal static string PICK_FAVORITE {
            get {
                return ResourceManager.GetString("PICK_FAVORITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose from black and white or color..
        /// </summary>
        internal static string SELECT_PHOTO_TYPE {
            get {
                return ResourceManager.GetString("SELECT_PHOTO_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for taking your photos!.
        /// </summary>
        internal static string THANK_YOU_FOR_TAKING_PHOTOS {
            get {
                return ResourceManager.GetString("THANK_YOU_FOR_TAKING_PHOTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the nav-tech photo booth..
        /// </summary>
        internal static string WELCOME {
            get {
                return ResourceManager.GetString("WELCOME", resourceCulture);
            }
        }
    }
}
