//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MME.Hercules.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MME.Hercules.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose up to {0} background{1}.  Default will be used if none selected!.
        /// </summary>
        internal static string CHOOSE_BG_INSTRUCTIONS_TEXT {
            get {
                return ResourceManager.GetString("CHOOSE_BG_INSTRUCTIONS_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choosebackground.jpg.
        /// </summary>
        internal static string CHOOSEBACKGROUND_SCREEN {
            get {
                return ResourceManager.GetString("CHOOSEBACKGROUND_SCREEN", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap chooseprint1 {
            get {
                object obj = ResourceManager.GetObject("chooseprint1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chooseprint2 {
            get {
                object obj = ResourceManager.GetObject("chooseprint2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chooseprint3 {
            get {
                object obj = ResourceManager.GetObject("chooseprint3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to developingpics.jpg.
        /// </summary>
        internal static string DEVELOPING_PICS_SCREEN {
            get {
                return ResourceManager.GetString("DEVELOPING_PICS_SCREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email.jpg.
        /// </summary>
        internal static string EMAIL_SCREEN {
            get {
                return ResourceManager.GetString("EMAIL_SCREEN", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap FLIP_THUMB_30x30 {
            get {
                object obj = ResourceManager.GetObject("FLIP-THUMB-30x30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FLIP_THUMB_30x30_flip {
            get {
                object obj = ResourceManager.GetObject("FLIP-THUMB-30x30-flip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make your selection in {0} second{1}.
        /// </summary>
        internal static string MAKE_SELECTION_TEXT {
            get {
                return ResourceManager.GetString("MAKE_SELECTION_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photomation_countdown_4.png.
        /// </summary>
        internal static string NUMBER_FOUR {
            get {
                return ResourceManager.GetString("NUMBER_FOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photomation_countdown_1.png.
        /// </summary>
        internal static string NUMBER_ONE {
            get {
                return ResourceManager.GetString("NUMBER_ONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photomation_countdown_3.png.
        /// </summary>
        internal static string NUMBER_THREE {
            get {
                return ResourceManager.GetString("NUMBER_THREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photomation_countdown_2.png.
        /// </summary>
        internal static string NUMBER_TWO {
            get {
                return ResourceManager.GetString("NUMBER_TWO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bg{0}.jpg.
        /// </summary>
        internal static string PHOTO_BACKGROUND_IMAGE {
            get {
                return ResourceManager.GetString("PHOTO_BACKGROUND_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photoscomplete.jpg.
        /// </summary>
        internal static string PHOTOS_COMPLETE_SCREEN {
            get {
                return ResourceManager.GetString("PHOTOS_COMPLETE_SCREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choosecolor.jpg.
        /// </summary>
        internal static string PHOTOTYPE_SCREEN {
            get {
                return ResourceManager.GetString("PHOTOTYPE_SCREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pickfavorite.jpg.
        /// </summary>
        internal static string PICK_FAVORITE_SCREEN {
            get {
                return ResourceManager.GetString("PICK_FAVORITE_SCREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to promo_complete.jpg.
        /// </summary>
        internal static string PROMO_COMPLETE {
            get {
                return ResourceManager.GetString("PROMO_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to promo.jpg.
        /// </summary>
        internal static string PROMO_SCREEN {
            get {
                return ResourceManager.GetString("PROMO_SCREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to roomnumber.jpg.
        /// </summary>
        internal static string ROOM_NUMBER_SCREEN {
            get {
                return ResourceManager.GetString("ROOM_NUMBER_SCREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selectbw.jpg.
        /// </summary>
        internal static string SELECTBW_IMAGE {
            get {
                return ResourceManager.GetString("SELECTBW_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selectcolor.jpg.
        /// </summary>
        internal static string SELECTCOLOR_IMAGE {
            get {
                return ResourceManager.GetString("SELECTCOLOR_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selectsepia.jpg.
        /// </summary>
        internal static string SELECTSEPIA_IMAGE {
            get {
                return ResourceManager.GetString("SELECTSEPIA_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smile!! We are now taking your {0} photo!.
        /// </summary>
        internal static string SMILE_TAKING_PHOTO_TEXT {
            get {
                return ResourceManager.GetString("SMILE_TAKING_PHOTO_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start.jpg.
        /// </summary>
        internal static string START_SCREEN {
            get {
                return ResourceManager.GetString("START_SCREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to survey.jpg.
        /// </summary>
        internal static string SURVEY {
            get {
                return ResourceManager.GetString("SURVEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to takephoto-flipped.jpg.
        /// </summary>
        internal static string TAKEPHOTO_FLIPPED_SCREEN {
            get {
                return ResourceManager.GetString("TAKEPHOTO_FLIPPED_SCREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to takephoto.jpg.
        /// </summary>
        internal static string TAKEPHOTO_SCREEN {
            get {
                return ResourceManager.GetString("TAKEPHOTO_SCREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thanksforphotos.jpg.
        /// </summary>
        internal static string THANKS_TAKING_PHOTOS_SCREEN {
            get {
                return ResourceManager.GetString("THANKS_TAKING_PHOTOS_SCREEN", resourceCulture);
            }
        }
    }
}
