//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://dev.virtualearth.net/webservices/v1/common", ClrNamespace="dev.virtualearth.net.webservices.v1.common")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://dev.virtualearth.net/webservices/v1/imagery", ClrNamespace="dev.virtualearth.net.webservices.v1.imagery")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://dev.virtualearth.net/webservices/v1/search", ClrNamespace="dev.virtualearth.net.webservices.v1.search")]

// 
// This code was auto-generated by slsvcutil, version 4.0.50303.0
// 
namespace dev.virtualearth.net.webservices.v1.common
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestBase", Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(dev.virtualearth.net.webservices.v1.imagery.MapUriRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(dev.virtualearth.net.webservices.v1.imagery.ImageryMetadataRequest))]
    public partial class RequestBase : object
    {
        
        private dev.virtualearth.net.webservices.v1.common.Credentials CredentialsField;
        
        private string CultureField;
        
        private dev.virtualearth.net.webservices.v1.common.ExecutionOptions ExecutionOptionsField;
        
        private dev.virtualearth.net.webservices.v1.common.UserProfile UserProfileField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.Credentials Credentials
        {
            get
            {
                return this.CredentialsField;
            }
            set
            {
                this.CredentialsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Culture
        {
            get
            {
                return this.CultureField;
            }
            set
            {
                this.CultureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.ExecutionOptions ExecutionOptions
        {
            get
            {
                return this.ExecutionOptionsField;
            }
            set
            {
                this.ExecutionOptionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.UserProfile UserProfile
        {
            get
            {
                return this.UserProfileField;
            }
            set
            {
                this.UserProfileField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Credentials", Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class Credentials : object
    {
        
        private string ApplicationIdField;
        
        private string TokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationId
        {
            get
            {
                return this.ApplicationIdField;
            }
            set
            {
                this.ApplicationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token
        {
            get
            {
                return this.TokenField;
            }
            set
            {
                this.TokenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExecutionOptions", Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class ExecutionOptions : object
    {
        
        private bool SuppressFaultsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SuppressFaults
        {
            get
            {
                return this.SuppressFaultsField;
            }
            set
            {
                this.SuppressFaultsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserProfile", Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class UserProfile : object
    {
        
        private dev.virtualearth.net.webservices.v1.common.Heading CurrentHeadingField;
        
        private dev.virtualearth.net.webservices.v1.common.UserLocation CurrentLocationField;
        
        private dev.virtualearth.net.webservices.v1.common.DeviceType DeviceTypeField;
        
        private dev.virtualearth.net.webservices.v1.common.DistanceUnit DistanceUnitField;
        
        private string IPAddressField;
        
        private dev.virtualearth.net.webservices.v1.common.ShapeBase MapViewField;
        
        private dev.virtualearth.net.webservices.v1.common.SizeOfint ScreenSizeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.Heading CurrentHeading
        {
            get
            {
                return this.CurrentHeadingField;
            }
            set
            {
                this.CurrentHeadingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.UserLocation CurrentLocation
        {
            get
            {
                return this.CurrentLocationField;
            }
            set
            {
                this.CurrentLocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.DeviceType DeviceType
        {
            get
            {
                return this.DeviceTypeField;
            }
            set
            {
                this.DeviceTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.DistanceUnit DistanceUnit
        {
            get
            {
                return this.DistanceUnitField;
            }
            set
            {
                this.DistanceUnitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IPAddress
        {
            get
            {
                return this.IPAddressField;
            }
            set
            {
                this.IPAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.ShapeBase MapView
        {
            get
            {
                return this.MapViewField;
            }
            set
            {
                this.MapViewField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.SizeOfint ScreenSize
        {
            get
            {
                return this.ScreenSizeField;
            }
            set
            {
                this.ScreenSizeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MapStyle", Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public enum MapStyle : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Road = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Aerial = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AerialWithLabels = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Birdseye = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BirdseyeWithLabels = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Heading", Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class Heading : object
    {
        
        private double OrientationField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Orientation
        {
            get
            {
                return this.OrientationField;
            }
            set
            {
                this.OrientationField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserLocation", Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class UserLocation : dev.virtualearth.net.webservices.v1.common.Location
    {
        
        private dev.virtualearth.net.webservices.v1.common.Confidence ConfidenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.Confidence Confidence
        {
            get
            {
                return this.ConfidenceField;
            }
            set
            {
                this.ConfidenceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShapeBase", Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(dev.virtualearth.net.webservices.v1.search.SearchPoint))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(dev.virtualearth.net.webservices.v1.common.Circle))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(dev.virtualearth.net.webservices.v1.common.Rectangle))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(dev.virtualearth.net.webservices.v1.common.Polygon))]
    public partial class ShapeBase : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SizeOfint", Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class SizeOfint : object
    {
        
        private int HeightField;
        
        private int WidthField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Height
        {
            get
            {
                return this.HeightField;
            }
            set
            {
                this.HeightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Width
        {
            get
            {
                return this.WidthField;
            }
            set
            {
                this.WidthField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeviceType", Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public enum DeviceType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Desktop = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Mobile = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DistanceUnit", Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public enum DistanceUnit : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Kilometer = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Mile = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Location", Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(dev.virtualearth.net.webservices.v1.common.GeocodeLocation))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(dev.virtualearth.net.webservices.v1.common.UserLocation))]
    public partial class Location : object
    {
        
        private double AltitudeField;
        
        private double LatitudeField;
        
        private double LongitudeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Altitude
        {
            get
            {
                return this.AltitudeField;
            }
            set
            {
                this.AltitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude
        {
            get
            {
                return this.LatitudeField;
            }
            set
            {
                this.LatitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longitude
        {
            get
            {
                return this.LongitudeField;
            }
            set
            {
                this.LongitudeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeocodeLocation", Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class GeocodeLocation : dev.virtualearth.net.webservices.v1.common.Location
    {
        
        private string CalculationMethodField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CalculationMethod
        {
            get
            {
                return this.CalculationMethodField;
            }
            set
            {
                this.CalculationMethodField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Confidence", Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public enum Confidence : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        High = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Medium = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Low = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Circle", Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class Circle : dev.virtualearth.net.webservices.v1.common.ShapeBase
    {
        
        private dev.virtualearth.net.webservices.v1.common.Location CenterField;
        
        private dev.virtualearth.net.webservices.v1.common.DistanceUnit DistanceUnitField;
        
        private double RadiusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.Location Center
        {
            get
            {
                return this.CenterField;
            }
            set
            {
                this.CenterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.DistanceUnit DistanceUnit
        {
            get
            {
                return this.DistanceUnitField;
            }
            set
            {
                this.DistanceUnitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Radius
        {
            get
            {
                return this.RadiusField;
            }
            set
            {
                this.RadiusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rectangle", Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class Rectangle : dev.virtualearth.net.webservices.v1.common.ShapeBase
    {
        
        private dev.virtualearth.net.webservices.v1.common.Location NortheastField;
        
        private dev.virtualearth.net.webservices.v1.common.Location SouthwestField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.Location Northeast
        {
            get
            {
                return this.NortheastField;
            }
            set
            {
                this.NortheastField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.Location Southwest
        {
            get
            {
                return this.SouthwestField;
            }
            set
            {
                this.SouthwestField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Polygon", Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class Polygon : dev.virtualearth.net.webservices.v1.common.ShapeBase
    {
        
        private dev.virtualearth.net.webservices.v1.common.Location[] VerticesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.Location[] Vertices
        {
            get
            {
                return this.VerticesField;
            }
            set
            {
                this.VerticesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pushpin", Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class Pushpin : object
    {
        
        private string IconStyleField;
        
        private string LabelField;
        
        private dev.virtualearth.net.webservices.v1.common.Location LocationField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IconStyle
        {
            get
            {
                return this.IconStyleField;
            }
            set
            {
                this.IconStyleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Label
        {
            get
            {
                return this.LabelField;
            }
            set
            {
                this.LabelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.Location Location
        {
            get
            {
                return this.LocationField;
            }
            set
            {
                this.LocationField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImageType", Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public enum ImageType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Default = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Png = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Jpeg = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Gif = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UriScheme", Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public enum UriScheme : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Http = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Https = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBase", Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(dev.virtualearth.net.webservices.v1.imagery.MapUriResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(dev.virtualearth.net.webservices.v1.imagery.ImageryMetadataResponse))]
    public partial class ResponseBase : object
    {
        
        private System.Uri BrandLogoUriField;
        
        private dev.virtualearth.net.webservices.v1.common.ResponseSummary ResponseSummaryField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Uri BrandLogoUri
        {
            get
            {
                return this.BrandLogoUriField;
            }
            set
            {
                this.BrandLogoUriField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.ResponseSummary ResponseSummary
        {
            get
            {
                return this.ResponseSummaryField;
            }
            set
            {
                this.ResponseSummaryField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseSummary", Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class ResponseSummary : object
    {
        
        private dev.virtualearth.net.webservices.v1.common.AuthenticationResultCode AuthenticationResultCodeField;
        
        private string CopyrightField;
        
        private string FaultReasonField;
        
        private dev.virtualearth.net.webservices.v1.common.ResponseStatusCode StatusCodeField;
        
        private string TraceIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.AuthenticationResultCode AuthenticationResultCode
        {
            get
            {
                return this.AuthenticationResultCodeField;
            }
            set
            {
                this.AuthenticationResultCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Copyright
        {
            get
            {
                return this.CopyrightField;
            }
            set
            {
                this.CopyrightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaultReason
        {
            get
            {
                return this.FaultReasonField;
            }
            set
            {
                this.FaultReasonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.ResponseStatusCode StatusCode
        {
            get
            {
                return this.StatusCodeField;
            }
            set
            {
                this.StatusCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TraceId
        {
            get
            {
                return this.TraceIdField;
            }
            set
            {
                this.TraceIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationResultCode", Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public enum AuthenticationResultCode : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoCredentials = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ValidCredentials = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidCredentials = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CredentialsExpired = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotAuthorized = 7,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseStatusCode", Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public enum ResponseStatusCode : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BadRequest = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ServerError = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RangeOfdateTime", Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class RangeOfdateTime : object
    {
        
        private System.DateTime FromField;
        
        private System.DateTime ToField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime From
        {
            get
            {
                return this.FromField;
            }
            set
            {
                this.FromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime To
        {
            get
            {
                return this.ToField;
            }
            set
            {
                this.ToField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RangeOfint", Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    public partial class RangeOfint : object
    {
        
        private int FromField;
        
        private int ToField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int From
        {
            get
            {
                return this.FromField;
            }
            set
            {
                this.FromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int To
        {
            get
            {
                return this.ToField;
            }
            set
            {
                this.ToField = value;
            }
        }
    }
}
namespace dev.virtualearth.net.webservices.v1.imagery
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MapUriRequest", Namespace="http://dev.virtualearth.net/webservices/v1/imagery")]
    public partial class MapUriRequest : dev.virtualearth.net.webservices.v1.common.RequestBase
    {
        
        private dev.virtualearth.net.webservices.v1.common.Location CenterField;
        
        private dev.virtualearth.net.webservices.v1.common.Location MajorRoutesDestinationField;
        
        private dev.virtualearth.net.webservices.v1.imagery.MapUriOptions OptionsField;
        
        private dev.virtualearth.net.webservices.v1.common.Pushpin[] PushpinsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.Location Center
        {
            get
            {
                return this.CenterField;
            }
            set
            {
                this.CenterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.Location MajorRoutesDestination
        {
            get
            {
                return this.MajorRoutesDestinationField;
            }
            set
            {
                this.MajorRoutesDestinationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.imagery.MapUriOptions Options
        {
            get
            {
                return this.OptionsField;
            }
            set
            {
                this.OptionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.Pushpin[] Pushpins
        {
            get
            {
                return this.PushpinsField;
            }
            set
            {
                this.PushpinsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImageryMetadataRequest", Namespace="http://dev.virtualearth.net/webservices/v1/imagery")]
    public partial class ImageryMetadataRequest : dev.virtualearth.net.webservices.v1.common.RequestBase
    {
        
        private dev.virtualearth.net.webservices.v1.imagery.ImageryMetadataOptions OptionsField;
        
        private dev.virtualearth.net.webservices.v1.common.MapStyle StyleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.imagery.ImageryMetadataOptions Options
        {
            get
            {
                return this.OptionsField;
            }
            set
            {
                this.OptionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.MapStyle Style
        {
            get
            {
                return this.StyleField;
            }
            set
            {
                this.StyleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImageryMetadataOptions", Namespace="http://dev.virtualearth.net/webservices/v1/imagery")]
    public partial class ImageryMetadataOptions : object
    {
        
        private dev.virtualearth.net.webservices.v1.common.Heading HeadingField;
        
        private dev.virtualearth.net.webservices.v1.common.Location LocationField;
        
        private bool ReturnImageryProvidersField;
        
        private dev.virtualearth.net.webservices.v1.common.UriScheme UriSchemeField;
        
        private System.Nullable<int> ZoomLevelField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.Heading Heading
        {
            get
            {
                return this.HeadingField;
            }
            set
            {
                this.HeadingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.Location Location
        {
            get
            {
                return this.LocationField;
            }
            set
            {
                this.LocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ReturnImageryProviders
        {
            get
            {
                return this.ReturnImageryProvidersField;
            }
            set
            {
                this.ReturnImageryProvidersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.UriScheme UriScheme
        {
            get
            {
                return this.UriSchemeField;
            }
            set
            {
                this.UriSchemeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ZoomLevel
        {
            get
            {
                return this.ZoomLevelField;
            }
            set
            {
                this.ZoomLevelField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MapUriOptions", Namespace="http://dev.virtualearth.net/webservices/v1/imagery")]
    public partial class MapUriOptions : object
    {
        
        private string[] DisplayLayersField;
        
        private dev.virtualearth.net.webservices.v1.common.SizeOfint ImageSizeField;
        
        private dev.virtualearth.net.webservices.v1.common.ImageType ImageTypeField;
        
        private bool PreventIconCollisionField;
        
        private dev.virtualearth.net.webservices.v1.common.MapStyle StyleField;
        
        private dev.virtualearth.net.webservices.v1.common.UriScheme UriSchemeField;
        
        private System.Nullable<int> ZoomLevelField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] DisplayLayers
        {
            get
            {
                return this.DisplayLayersField;
            }
            set
            {
                this.DisplayLayersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.SizeOfint ImageSize
        {
            get
            {
                return this.ImageSizeField;
            }
            set
            {
                this.ImageSizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.ImageType ImageType
        {
            get
            {
                return this.ImageTypeField;
            }
            set
            {
                this.ImageTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PreventIconCollision
        {
            get
            {
                return this.PreventIconCollisionField;
            }
            set
            {
                this.PreventIconCollisionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.MapStyle Style
        {
            get
            {
                return this.StyleField;
            }
            set
            {
                this.StyleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.UriScheme UriScheme
        {
            get
            {
                return this.UriSchemeField;
            }
            set
            {
                this.UriSchemeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ZoomLevel
        {
            get
            {
                return this.ZoomLevelField;
            }
            set
            {
                this.ZoomLevelField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MapUriResponse", Namespace="http://dev.virtualearth.net/webservices/v1/imagery")]
    public partial class MapUriResponse : dev.virtualearth.net.webservices.v1.common.ResponseBase
    {
        
        private string UriField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Uri
        {
            get
            {
                return this.UriField;
            }
            set
            {
                this.UriField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImageryMetadataResponse", Namespace="http://dev.virtualearth.net/webservices/v1/imagery")]
    public partial class ImageryMetadataResponse : dev.virtualearth.net.webservices.v1.common.ResponseBase
    {
        
        private dev.virtualearth.net.webservices.v1.imagery.ImageryMetadataResult[] ResultsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.imagery.ImageryMetadataResult[] Results
        {
            get
            {
                return this.ResultsField;
            }
            set
            {
                this.ResultsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImageryMetadataResult", Namespace="http://dev.virtualearth.net/webservices/v1/imagery")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(dev.virtualearth.net.webservices.v1.imagery.ImageryMetadataBirdseyeResult))]
    public partial class ImageryMetadataResult : object
    {
        
        private dev.virtualearth.net.webservices.v1.common.SizeOfint ImageSizeField;
        
        private string ImageUriField;
        
        private string[] ImageUriSubdomainsField;
        
        private dev.virtualearth.net.webservices.v1.imagery.ImageryProvider[] ImageryProvidersField;
        
        private dev.virtualearth.net.webservices.v1.common.RangeOfdateTime VintageField;
        
        private dev.virtualearth.net.webservices.v1.common.RangeOfint ZoomRangeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.SizeOfint ImageSize
        {
            get
            {
                return this.ImageSizeField;
            }
            set
            {
                this.ImageSizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUri
        {
            get
            {
                return this.ImageUriField;
            }
            set
            {
                this.ImageUriField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ImageUriSubdomains
        {
            get
            {
                return this.ImageUriSubdomainsField;
            }
            set
            {
                this.ImageUriSubdomainsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.imagery.ImageryProvider[] ImageryProviders
        {
            get
            {
                return this.ImageryProvidersField;
            }
            set
            {
                this.ImageryProvidersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.RangeOfdateTime Vintage
        {
            get
            {
                return this.VintageField;
            }
            set
            {
                this.VintageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.RangeOfint ZoomRange
        {
            get
            {
                return this.ZoomRangeField;
            }
            set
            {
                this.ZoomRangeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImageryMetadataBirdseyeResult", Namespace="http://dev.virtualearth.net/webservices/v1/imagery")]
    public partial class ImageryMetadataBirdseyeResult : dev.virtualearth.net.webservices.v1.imagery.ImageryMetadataResult
    {
        
        private dev.virtualearth.net.webservices.v1.common.Heading HeadingField;
        
        private int TilesXField;
        
        private int TilesYField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.Heading Heading
        {
            get
            {
                return this.HeadingField;
            }
            set
            {
                this.HeadingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TilesX
        {
            get
            {
                return this.TilesXField;
            }
            set
            {
                this.TilesXField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TilesY
        {
            get
            {
                return this.TilesYField;
            }
            set
            {
                this.TilesYField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImageryProvider", Namespace="http://dev.virtualearth.net/webservices/v1/imagery")]
    public partial class ImageryProvider : object
    {
        
        private string AttributionField;
        
        private dev.virtualearth.net.webservices.v1.imagery.CoverageArea[] CoverageAreasField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Attribution
        {
            get
            {
                return this.AttributionField;
            }
            set
            {
                this.AttributionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.imagery.CoverageArea[] CoverageAreas
        {
            get
            {
                return this.CoverageAreasField;
            }
            set
            {
                this.CoverageAreasField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CoverageArea", Namespace="http://dev.virtualearth.net/webservices/v1/imagery")]
    public partial class CoverageArea : object
    {
        
        private dev.virtualearth.net.webservices.v1.common.Rectangle BoundingRectangleField;
        
        private dev.virtualearth.net.webservices.v1.common.RangeOfint ZoomRangeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.Rectangle BoundingRectangle
        {
            get
            {
                return this.BoundingRectangleField;
            }
            set
            {
                this.BoundingRectangleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.RangeOfint ZoomRange
        {
            get
            {
                return this.ZoomRangeField;
            }
            set
            {
                this.ZoomRangeField = value;
            }
        }
    }
}
namespace dev.virtualearth.net.webservices.v1.search
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchPoint", Namespace="http://dev.virtualearth.net/webservices/v1/search")]
    public partial class SearchPoint : dev.virtualearth.net.webservices.v1.common.ShapeBase
    {
        
        private dev.virtualearth.net.webservices.v1.common.Location PointField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public dev.virtualearth.net.webservices.v1.common.Location Point
        {
            get
            {
                return this.PointField;
            }
            set
            {
                this.PointField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/imagery/contracts", ConfigurationName="IImageryService")]
public interface IImageryService
{
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://dev.virtualearth.net/webservices/v1/imagery/contracts/IImageryService/GetI" +
        "mageryMetadata", ReplyAction="http://dev.virtualearth.net/webservices/v1/imagery/contracts/IImageryService/GetI" +
        "mageryMetadataResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(dev.virtualearth.net.webservices.v1.common.ResponseSummary), Action="http://dev.virtualearth.net/webservices/v1/imagery/contracts/IImageryService/GetI" +
        "mageryMetadataResponseSummaryFault", Name="ResponseSummary", Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    System.IAsyncResult BeginGetImageryMetadata(dev.virtualearth.net.webservices.v1.imagery.ImageryMetadataRequest request, System.AsyncCallback callback, object asyncState);
    
    dev.virtualearth.net.webservices.v1.imagery.ImageryMetadataResponse EndGetImageryMetadata(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://dev.virtualearth.net/webservices/v1/imagery/contracts/IImageryService/GetM" +
        "apUri", ReplyAction="http://dev.virtualearth.net/webservices/v1/imagery/contracts/IImageryService/GetM" +
        "apUriResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(dev.virtualearth.net.webservices.v1.common.ResponseSummary), Action="http://dev.virtualearth.net/webservices/v1/imagery/contracts/IImageryService/GetM" +
        "apUriResponseSummaryFault", Name="ResponseSummary", Namespace="http://dev.virtualearth.net/webservices/v1/common")]
    System.IAsyncResult BeginGetMapUri(dev.virtualearth.net.webservices.v1.imagery.MapUriRequest request, System.AsyncCallback callback, object asyncState);
    
    dev.virtualearth.net.webservices.v1.imagery.MapUriResponse EndGetMapUri(System.IAsyncResult result);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IImageryServiceChannel : IImageryService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class GetImageryMetadataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetImageryMetadataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public dev.virtualearth.net.webservices.v1.imagery.ImageryMetadataResponse Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((dev.virtualearth.net.webservices.v1.imagery.ImageryMetadataResponse)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class GetMapUriCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetMapUriCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public dev.virtualearth.net.webservices.v1.imagery.MapUriResponse Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((dev.virtualearth.net.webservices.v1.imagery.MapUriResponse)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class ImageryServiceClient : System.ServiceModel.ClientBase<IImageryService>, IImageryService
{
    
    private BeginOperationDelegate onBeginGetImageryMetadataDelegate;
    
    private EndOperationDelegate onEndGetImageryMetadataDelegate;
    
    private System.Threading.SendOrPostCallback onGetImageryMetadataCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetMapUriDelegate;
    
    private EndOperationDelegate onEndGetMapUriDelegate;
    
    private System.Threading.SendOrPostCallback onGetMapUriCompletedDelegate;
    
    private BeginOperationDelegate onBeginOpenDelegate;
    
    private EndOperationDelegate onEndOpenDelegate;
    
    private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
    
    private BeginOperationDelegate onBeginCloseDelegate;
    
    private EndOperationDelegate onEndCloseDelegate;
    
    private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
    
    public ImageryServiceClient()
    {
    }
    
    public ImageryServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ImageryServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ImageryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ImageryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Net.CookieContainer CookieContainer
    {
        get
        {
            System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
            if ((httpCookieContainerManager != null))
            {
                return httpCookieContainerManager.CookieContainer;
            }
            else
            {
                return null;
            }
        }
        set
        {
            System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
            if ((httpCookieContainerManager != null))
            {
                httpCookieContainerManager.CookieContainer = value;
            }
            else
            {
                throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                        "ookieContainerBindingElement.");
            }
        }
    }
    
    public event System.EventHandler<GetImageryMetadataCompletedEventArgs> GetImageryMetadataCompleted;
    
    public event System.EventHandler<GetMapUriCompletedEventArgs> GetMapUriCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IImageryService.BeginGetImageryMetadata(dev.virtualearth.net.webservices.v1.imagery.ImageryMetadataRequest request, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetImageryMetadata(request, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    dev.virtualearth.net.webservices.v1.imagery.ImageryMetadataResponse IImageryService.EndGetImageryMetadata(System.IAsyncResult result)
    {
        return base.Channel.EndGetImageryMetadata(result);
    }
    
    private System.IAsyncResult OnBeginGetImageryMetadata(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        dev.virtualearth.net.webservices.v1.imagery.ImageryMetadataRequest request = ((dev.virtualearth.net.webservices.v1.imagery.ImageryMetadataRequest)(inValues[0]));
        return ((IImageryService)(this)).BeginGetImageryMetadata(request, callback, asyncState);
    }
    
    private object[] OnEndGetImageryMetadata(System.IAsyncResult result)
    {
        dev.virtualearth.net.webservices.v1.imagery.ImageryMetadataResponse retVal = ((IImageryService)(this)).EndGetImageryMetadata(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetImageryMetadataCompleted(object state)
    {
        if ((this.GetImageryMetadataCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetImageryMetadataCompleted(this, new GetImageryMetadataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetImageryMetadataAsync(dev.virtualearth.net.webservices.v1.imagery.ImageryMetadataRequest request)
    {
        this.GetImageryMetadataAsync(request, null);
    }
    
    public void GetImageryMetadataAsync(dev.virtualearth.net.webservices.v1.imagery.ImageryMetadataRequest request, object userState)
    {
        if ((this.onBeginGetImageryMetadataDelegate == null))
        {
            this.onBeginGetImageryMetadataDelegate = new BeginOperationDelegate(this.OnBeginGetImageryMetadata);
        }
        if ((this.onEndGetImageryMetadataDelegate == null))
        {
            this.onEndGetImageryMetadataDelegate = new EndOperationDelegate(this.OnEndGetImageryMetadata);
        }
        if ((this.onGetImageryMetadataCompletedDelegate == null))
        {
            this.onGetImageryMetadataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetImageryMetadataCompleted);
        }
        base.InvokeAsync(this.onBeginGetImageryMetadataDelegate, new object[] {
                    request}, this.onEndGetImageryMetadataDelegate, this.onGetImageryMetadataCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IImageryService.BeginGetMapUri(dev.virtualearth.net.webservices.v1.imagery.MapUriRequest request, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetMapUri(request, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    dev.virtualearth.net.webservices.v1.imagery.MapUriResponse IImageryService.EndGetMapUri(System.IAsyncResult result)
    {
        return base.Channel.EndGetMapUri(result);
    }
    
    private System.IAsyncResult OnBeginGetMapUri(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        dev.virtualearth.net.webservices.v1.imagery.MapUriRequest request = ((dev.virtualearth.net.webservices.v1.imagery.MapUriRequest)(inValues[0]));
        return ((IImageryService)(this)).BeginGetMapUri(request, callback, asyncState);
    }
    
    private object[] OnEndGetMapUri(System.IAsyncResult result)
    {
        dev.virtualearth.net.webservices.v1.imagery.MapUriResponse retVal = ((IImageryService)(this)).EndGetMapUri(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetMapUriCompleted(object state)
    {
        if ((this.GetMapUriCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetMapUriCompleted(this, new GetMapUriCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetMapUriAsync(dev.virtualearth.net.webservices.v1.imagery.MapUriRequest request)
    {
        this.GetMapUriAsync(request, null);
    }
    
    public void GetMapUriAsync(dev.virtualearth.net.webservices.v1.imagery.MapUriRequest request, object userState)
    {
        if ((this.onBeginGetMapUriDelegate == null))
        {
            this.onBeginGetMapUriDelegate = new BeginOperationDelegate(this.OnBeginGetMapUri);
        }
        if ((this.onEndGetMapUriDelegate == null))
        {
            this.onEndGetMapUriDelegate = new EndOperationDelegate(this.OnEndGetMapUri);
        }
        if ((this.onGetMapUriCompletedDelegate == null))
        {
            this.onGetMapUriCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetMapUriCompleted);
        }
        base.InvokeAsync(this.onBeginGetMapUriDelegate, new object[] {
                    request}, this.onEndGetMapUriDelegate, this.onGetMapUriCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
    }
    
    private object[] OnEndOpen(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
        return null;
    }
    
    private void OnOpenCompleted(object state)
    {
        if ((this.OpenCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void OpenAsync()
    {
        this.OpenAsync(null);
    }
    
    public void OpenAsync(object userState)
    {
        if ((this.onBeginOpenDelegate == null))
        {
            this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
        }
        if ((this.onEndOpenDelegate == null))
        {
            this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
        }
        if ((this.onOpenCompletedDelegate == null))
        {
            this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
        }
        base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
    }
    
    private object[] OnEndClose(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
        return null;
    }
    
    private void OnCloseCompleted(object state)
    {
        if ((this.CloseCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void CloseAsync()
    {
        this.CloseAsync(null);
    }
    
    public void CloseAsync(object userState)
    {
        if ((this.onBeginCloseDelegate == null))
        {
            this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
        }
        if ((this.onEndCloseDelegate == null))
        {
            this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
        }
        if ((this.onCloseCompletedDelegate == null))
        {
            this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
        }
        base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
    }
    
    protected override IImageryService CreateChannel()
    {
        return new ImageryServiceClientChannel(this);
    }
    
    private class ImageryServiceClientChannel : ChannelBase<IImageryService>, IImageryService
    {
        
        public ImageryServiceClientChannel(System.ServiceModel.ClientBase<IImageryService> client) : 
                base(client)
        {
        }
        
        public System.IAsyncResult BeginGetImageryMetadata(dev.virtualearth.net.webservices.v1.imagery.ImageryMetadataRequest request, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = request;
            System.IAsyncResult _result = base.BeginInvoke("GetImageryMetadata", _args, callback, asyncState);
            return _result;
        }
        
        public dev.virtualearth.net.webservices.v1.imagery.ImageryMetadataResponse EndGetImageryMetadata(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            dev.virtualearth.net.webservices.v1.imagery.ImageryMetadataResponse _result = ((dev.virtualearth.net.webservices.v1.imagery.ImageryMetadataResponse)(base.EndInvoke("GetImageryMetadata", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetMapUri(dev.virtualearth.net.webservices.v1.imagery.MapUriRequest request, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = request;
            System.IAsyncResult _result = base.BeginInvoke("GetMapUri", _args, callback, asyncState);
            return _result;
        }
        
        public dev.virtualearth.net.webservices.v1.imagery.MapUriResponse EndGetMapUri(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            dev.virtualearth.net.webservices.v1.imagery.MapUriResponse _result = ((dev.virtualearth.net.webservices.v1.imagery.MapUriResponse)(base.EndInvoke("GetMapUri", _args, result)));
            return _result;
        }
    }
}
